name: "Deployable Workspaces"
description: "Get all deployable workspaces found in the monorepo"
inputs:
  who-to-greet: # id of input
    description: "Who to greet"
    required: true
    default: "World"
outputs:
  deployable_workspaces:
    description: "The deployable workspaces"
    value: ${{ steps.list_workspaces.outputs.deployable_workspaces }}
runs:
  using: "composite"
  steps:
    - name: Set GitHub Path
      run: echo "$GITHUB_ACTION_PATH/scripts" >> $GITHUB_PATH
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}
    - id: list_workspaces
      run: list_workspaces.sh
      shell: bash
