name: "Workspaces Helper"
description: "Get all kinds of information about the workspaces found in the monorepo"
inputs:
  workspace_filter_key:
    description: "The key to filter the workspaces by"
    required: false
outputs:
  workspaces_filtered:
    description: "The filtered workspaces as json array. Use fromJSON in your github workflow."
    value: ${{ steps.workspaces.outputs.workspaces_filtered }}
runs:
  using: "composite"
  steps:
    - name: Set GitHub Path
      run: echo "$GITHUB_ACTION_PATH/scripts" >> $GITHUB_PATH
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}
    - id: workspaces
      run: |
        source ${{ github.action_path }}/scripts/workspaces.sh
        workspace_filter_key="${{ inputs.workspace_filter_key }}"
        if [[ -n "$workspace_filter_key" ]]; then
          workspaces_filtered="$(filter_workspaces "$workspace_filter_key")"
        else
          workspaces_filtered="[]"
        fi
        echo "workspaces_filtered=$workspaces_filtered"
        echo "workspaces_filtered=$workspaces_filtered" >> $GITHUB_OUTPUT
      shell: bash
