name: "Workspaces Helper"
description: "Get all kinds of information about the workspaces found in the monorepo"
inputs:
  workspace_filter_key:
    description: "The key to filter the workspaces by"
    required: false
outputs:
  workspace_matrix_filtered:
    description: "The filteredworkspaces"
    value: ${{ steps.workspaces.outputs.workspace_matrix_filtered }}
runs:
  using: "composite"
  steps:
    - name: Set GitHub Path
      run: echo "$GITHUB_ACTION_PATH/scripts" >> $GITHUB_PATH
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}
    - id: workspaces
      run: |
        source ${{ github.action_path }}/scripts/workspaces.sh
        workspace_filter_key="${{ inputs.workspace_filter_key }}"
        if [[ -n "$workspace_filter_key" ]]; then
          workspace_matrix_filtered="$(filter_workspaces "$workspace_filter_key")"
        else
          workspace_matrix_filtered="{\"include\":[]}"
        fi
        echo "workspace_matrix_filtered=$workspace_matrix_filtered"
        echo "workspace_matrix_filtered=$workspace_matrix_filtered" >> $GITHUB_OUTPUT
      shell: bash
