name: Deploy to Fly 🪰

concurrency:
  group: ${{ github.repository }}-${{ github.workflow }}-${{ github.ref }}-${{ inputs.fly_app_name }}-${{ inputs.github_environment }}
  cancel-in-progress: true

on:
  workflow_call:
    outputs:
      app_name:
        value: ${{ jobs.deploy.outputs.app_name }}
        description: "The name of the deployed app"
      app_url:
        value: ${{ jobs.deploy.outputs.app_url }}
        description: "The url of the deployed app"
      app_normalized_name:
        value: ${{ jobs.deploy.outputs.app_normalized_name }}
        description: "The name of the deployed app"

    inputs:
      workspace_name:
        required: false
        type: string
        description: "The name of the workspace to deploy. This is used to find the folder of the workspace by searching name fields in all package.json files."
      fly_app_name:
        required: false
        type: string
        description: "The name of the fly app to deploy."
      github_environment:
        required: true
        type: string
        description: "The name of the github deployment environment to deploy"
      fly_config_file_path:
        required: false
        type: string
        description: "Relative workspace path of the fly config file. Defaults to './fly.toml'"
        default: "./fly.toml"
      fly_org:
        required: false
        default: ${{ vars.FLY_ORG }}
        type: string
        description: "The Fly Organization to deploy to"
      fly_consul_attach:
        required: false
        type: boolean
        description: "Whether to attach a consul cluster to the app. Defaults to false"
        default: false
      deploy_timeout_minutes:
        required: false
        type: number
        description: "The timeout for the deployment in minutes. Defaults to 20 minutes"
        default: 20
      needs_deploy:
        required: false
        description: "Whether to deploy the app or not. Defaults to true. You can use this to dynamically decided if the workspace needs to be deployed or not."
        type: boolean
        default: true

    secrets:
      fly_secrets:
        required: false
        description: "The secrets to import to the app, separated by newlines"
      fly_api_token:
        required: true
        description: "The Fly API token"

env:
  FLY_API_TOKEN: ${{ secrets.fly_api_token }}

jobs:
  deploy:
    if: ${{ inputs.needs_deploy }}
    name: "${{ inputs.github_environment }}"
    runs-on: ubuntu-latest
    outputs:
      app_name: ${{ steps.fly_deploy.outputs.app_name }}
      app_url: ${{ steps.fly_deploy.outputs.app_url }}
      app_normalized_name: ${{ steps.fly_deploy.outputs.app_normalized_name }}
    environment:
      name: ${{ inputs.github_environment }}
      url: ${{ steps.fly_deploy.outputs.app_url }}
    timeout-minutes: ${{ inputs.deploy_timeout_minutes }}
    env:
      #LOG_LEVEL: debug
      NO_COLOR: 1
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - uses: actions/checkout@v4
        with:
          repository: forge42dev/workflows
          ref: monorepo-matrix
          path: ".workflows"
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - id: fly_deploy
        run: |
          # Deploy the app to fly.io
          source .workflows/scripts/retry
          source .workflows/scripts/prepare-vars

          prepare_vars '${{ toJSON(inputs) }}' '{ "github": { "repository": "${{ github.repository }}", "event_name": "${{ github.event_name }}", "ref_name": "${{ github.ref_name }}", "ref_type": "${{ github.ref_type }}", "sha": "${{ github.sha }}", "event": { "number": "${{ github.event.number }}", "pull_request": { "head": { "sha": "${{ github.event.pull_request.head.sha }}" } } } } }'

          notice "workspace_path=$workspace_path"
          notice "workspace_name=$workspace_name"
          notice "fly_app_name=$fly_app_name"
          notice "fly_config_file_path=$fly_config_file_path"
          notice "git_commit_sha=$git_commit_sha"
          notice "git_commit_sha_short=$git_commit_sha_short"

          # Check if the app already exists, if not, create it.
          # We want to have that in a separate group, thats the reason why we use status and create
          # in two separate steps
          echo "::group::Check if fly app '$fly_app_name' already exists"
          fly_status=0
          if ! flyctl status --app "$fly_app_name"; then
            fly_status=1
          fi
          echo "::endgroup::" # Check if fly app already exists

          if [ $fly_status -ne 0 ]; then
            echo "::warning::App '$fly_app_name' does not exist, creating it..."
            retry 5 2 "Create fly app '$fly_app_name'" flyctl apps create "$fly_app_name" --org "${{ inputs.fly_org }}"
          else
            echo "::notice::App '$fly_app_name' already exists, skipping creation."
          fi

          # Import secrets if any
          echo "::group::Set the fly secrets if any are set"
          if [ -n "${{ secrets.fly_secrets }}" ]; then
            echo '::notice::fly_secrets=${{ secrets.fly_secrets }}'
            echo '${{ secrets.fly_secrets }}' | tr " " "\n" | flyctl secrets import --stage --app "$fly_app_name";
          else
            echo "::warning::No secrets to import!";
          fi
          echo "::endgroup::"

          # Attach a consul cluster if requested
          if [ "${{ inputs.fly_consul_attach }}" == "true" ]; then
            retry 5 2 "Attaching a consul cluster" flyctl consul attach --app "$fly_app_name"
          fi

          # Deploy/Update the app
          retry 5 2 "Deploy the app to fly.io" flyctl deploy \
            --config "$fly_config_file_path" \
            --app "$fly_app_name" \
            --build-arg "GIT_SHA=$git_commit_sha_short" \
            --remote-only \
            --now \
            --yes

          # Get the app url
          echo "::group::Get the app url"
          app_url="https://$(flyctl status --app "$fly_app_name" --json | jq -rS '.Hostname')/"

          # Set the app url as an github output
          echo "::notice::app_url=$app_url"
          echo "app_url=$app_url" >> $GITHUB_OUTPUT
          echo "::endgroup::"

          echo "### Deployed ${{ inputs.app_name }} :rocket:" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "App URL: $app_url" >> $GITHUB_STEP_SUMMARY
