name: Deploy to Fly 🪰

concurrency:
  group: ${{ github.repository }}-${{ github.workflow }}-${{ github.ref }}-${{ inputs.app_name }}-${{ inputs.github_environment }}
  cancel-in-progress: true

on:
  workflow_call:
    outputs:
      app_name:
        value: ${{ jobs.deploy.outputs.app_name }}
        description: "The name of the deployed app"
      app_url:
        value: ${{ jobs.deploy.outputs.app_url }}
        description: "The url of the deployed app"
      app_normalized_name:
        value: ${{ jobs.deploy.outputs.app_normalized_name }}
        description: "The name of the deployed app"

    inputs:
      app_name:
        required: false
        type: string
        description: "The name of the workspace to deploy. This will be used to find the workspace path and app name"
      github_environment:
        required: true
        type: string
        description: "The name of the github deployment environment to deploy"
      fly_org:
        required: true
        type: string
        description: "The Fly Organization to deploy to"
      app_stage:
        required: false
        type: string
        description: "The stage of the app which will be deployed. Defaults to 'staging'"
        default: "staging"
      deploy_timeout_minutes:
        required: false
        type: number
        description: "The timeout for the deployment in minutes. Defaults to 20 minutes"
        default: 20
      needs_deploy:
        required: false
        description: "Whether to deploy the app or not. Defaults to true. You can use this to dynamically decided if the workspace needs to be deployed or not."
        type: boolean
        default: true

    secrets:
      fly_secrets:
        required: false
        description: "The secrets to import to the app, separated by newlines"
      fly_api_token:
        required: true
        description: "The Fly API token"

env:
  FLY_API_TOKEN: ${{ secrets.fly_api_token }}

jobs:
  deploy:
    if: ${{ inputs.needs_deploy }}
    name: "${{ inputs.github_environment }}"
    runs-on: ubuntu-latest
    outputs:
      app_name: ${{ steps.fly_deploy.outputs.app_name }}
      app_url: ${{ steps.fly_deploy.outputs.app_url }}
      app_normalized_name: ${{ steps.fly_deploy.outputs.app_normalized_name }}
    environment:
      name: ${{ inputs.github_environment }}
      url: ${{ steps.fly_deploy.outputs.app_url }}
    timeout-minutes: ${{ inputs.deploy_timeout_minutes }}
    env:
      #LOG_LEVEL: debug
      NO_COLOR: 1
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - id: fly_deploy
        run: |
          # Deploy the app to fly.io

          # Exponential backoff retry function
          # retry <retries> <base sleep time in seconds> <command...>
          function retry {
            local retries=$1
            shift
            local base=$1
            shift
            local group_name=$1
            shift

            local count=1

            echo "::group::Try '$group_name ($count/$retries)'."
            echo "::notice::Using command: '$@'"

            until "$@"; do
              exit=$?

              echo "::error::'$group_name ($count/$retries)' exited with '$exit'."
              echo "::endgroup::"

              count=$(($count + 1))
              wait=$(($base ** $count))

              if [ $count -le $retries ]; then
                echo "::notice::Start retry for '$group_name ($count/$retries)' in '$wait' seconds."
                sleep $wait
                echo "::group::Retry '$group_name ($count/$retries)'."
                echo "::notice::Using command: '$@'"
              else
                echo "::error::No more retries left for '$group_name ($count/$retries)'. Exiting with exit code '$exit'."
                return $exit
              fi
            done
            echo "::endgroup::"
            return 0
          }

          shopt -s globstar

          echo "::group::Prepare variables needed for deployment"

          if [ -z "${{ inputs.app_name }}" ]; then
            app_name="${{ github.repository }}"
            # If the app name is not set, the absolute path of the workspace is the current directory
            workspace_path="./"
            absolute_workspace_path="$(dirname "$(pwd)/$workspace_path")"
          else
            app_name="${{ inputs.app_name }}"
            # Get the absolute path of the workspace.
            # e.g. '/path/to/monorepo/apps/external/the-workspace'
            workspace_path="$(grep -rls '"name":.*"${{ inputs.app_name }}"' **/package.json | xargs -I {} dirname {})"
            absolute_workspace_path="$(pwd)/$workspace_path"
            # If no workspace is found, exit with an error
            if [ -z "$workspace_path" ]; then
              echo "::error::No workspace with name '${{ inputs.app_name }}' found.";
              exit 1;
            fi
          fi

          echo "::notice::app_name=$app_name"
          echo "app_name=$app_name" >> $GITHUB_OUTPUT

          echo "::notice::absolute_workspace_path=$absolute_workspace_path"

          echo "::notice::workspace_path=$workspace_path"
          echo "workspace_path=$workspace_path" >> $GITHUB_OUTPUT


          if [ "${{ github.event_name }}" == "pull_request" ]; then
            git_sha="$(git rev-parse --short ${{github.event.pull_request.head.sha}})"
          else
            git_sha="$(git rev-parse --short $GITHUB_SHA)"
          fi

          echo "::notice::git_sha=$git_sha"
          echo "git_sha=$git_sha" >> $GITHUB_OUTPUT

          # Get the app name, replaces '/' and '.' with '-', everything else gets removed to make it url friendly
          # e.g. 'octo-CAT/monorepo-stack_@some_WORKSPACE?foo=bar' => 'octo-cat-monorepo-stack-some-workspacefoobar'
          app_normalized_name="$(echo $app_name | sed 's/[\.\/_]/-/g; s/[^a-zA-Z0-9-]//g' | tr '[:upper:]' '[:lower:]')"

          # Set the app name as an github output
          echo "::notice::app_normalized_name=$app_normalized_name"
          echo "app_normalized_name=$app_normalized_name" >> $GITHUB_OUTPUT

          echo "::endgroup::" # Prepare variables needed for deployment

          # Check if the app already exists, if not, create it
          echo "::group::Check if fly app '$app_normalized_name' already exists"
          flyctl status --app "$app_normalized_name"
          fly_status=$?
          echo "::endgroup::"

          if [ $fly_status -ne 0 ]; then
            echo "::warning::App '$app_normalized_name' does not exist, creating it..."
            retry 5 4 "Create fly app '$app_normalized_name'" flyctl apps create "$app_normalized_name" --org "${{ inputs.fly_org }}"
          fi

          # Import secrets if any
          echo "::group::Set the fly secrets if any are set"
          if [ -n "${{ secrets.fly_secrets }}" ]; then
            echo '::notice::fly_secrets=${{ secrets.fly_secrets }}'
            echo '${{ secrets.fly_secrets }}' | tr " " "\n" | flyctl secrets import --stage --app "$app_normalized_name";
          else
            echo "::warning::No secrets to import!";
          fi
          echo "::endgroup::"

          # Deploy/Update the app
          retry 5 4 "Deploy the app to fly.io" flyctl deploy \
            --config "$absolute_workspace_path/fly.${{ inputs.app_stage }}.toml" \
            --app "$app_normalized_name" \
            --build-arg "GIT_SHA=$git_sha" \
            --remote-only \
            --now \
            --yes

          # Get the app url
          echo "::group::Get the app url"
          app_url="https://$(flyctl status --app "$app_normalized_name" --json | jq -rS '.Hostname')/"

          # Set the app url as an github output
          echo "::notice::app_url=$app_url"
          echo "app_url=$app_url" >> $GITHUB_OUTPUT
          echo "::endgroup::"

          echo "### Deployed ${{ inputs.app_name }} :rocket:" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "App URL: $app_url" >> $GITHUB_STEP_SUMMARY
