name: Deploy to Fly 🪰

concurrency:
  group: ${{ github.repository }}-${{ github.workflow }}-${{ github.ref }}-${{ inputs.fly_app_name }}-${{ inputs.github_environment }}
  cancel-in-progress: true

on:
  workflow_call:
    outputs:
      fly_app_name:
        value: ${{ jobs.deploy.outputs.fly_app_name }}
        description: "The name of the deployed app"
      fly_app_url:
        value: ${{ jobs.deploy.outputs.app_url }}
        description: "The url of the deployed app"
      workspace_name:
        value: ${{ jobs.deploy.outputs.workspace_name }}
        description: "The name of the workspace"
      workspace_path:
        value: ${{ jobs.deploy.outputs.workspace_path }}
        description: "The path of the workspace"

    inputs:
      workspace_name:
        required: false
        type: string
        description: "The name of the workspace to deploy. This is used to find the folder of the workspace by searching name fields in all package.json files."
      fly_app_name:
        required: false
        type: string
        description: "The name of the fly app to deploy."
      github_environment:
        required: true
        type: string
        description: "The name of the github deployment environment to deploy"
      fly_config_file_path:
        required: false
        type: string
        description: "Relative workspace path of the fly config file. Defaults to './fly.toml'"
        default: "./fly.toml"
      fly_org:
        required: false
        default: ${{ vars.FLY_ORG }}
        type: string
        description: "The Fly Organization to deploy to"
      fly_consul_attach:
        required: false
        type: boolean
        description: "Whether to attach a consul cluster to the app. Defaults to false"
        default: false
      deploy_timeout_minutes:
        required: false
        type: number
        description: "The timeout for the deployment in minutes. Defaults to 20 minutes"
        default: 20
      needs_deploy:
        required: false
        description: "Whether to deploy the app or not. Defaults to true. You can use this to dynamically decided if the workspace needs to be deployed or not."
        type: boolean
        default: true

    secrets:
      fly_secrets:
        required: false
        description: "The secrets to import to the app, separated by newlines"
      fly_api_token:
        required: true
        description: "The Fly API token"

env:
  FLY_API_TOKEN: ${{ secrets.fly_api_token }}

jobs:
  deploy:
    if: ${{ inputs.needs_deploy }}
    name: "${{ inputs.github_environment }}"
    runs-on: ubuntu-latest
    outputs:
      fly_app_name: ${{ steps.fly_deploy.outputs.fly_app_name }}
      fly_app_url: ${{ steps.fly_deploy.outputs.fly_app_url }}
      workspace_name: ${{ steps.fly_deploy.outputs.workspace_name }}
      workspace_path: ${{ steps.fly_deploy.outputs.workspace_path }}
    environment:
      name: ${{ inputs.github_environment }}
      url: ${{ steps.fly_deploy.outputs.app_url }}
    timeout-minutes: ${{ inputs.deploy_timeout_minutes }}
    # env:
      #LOG_LEVEL: debug
      # NO_COLOR: 1
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - uses: actions/checkout@v4
        with:
          repository: forge42dev/workflows
          ref: monorepo-matrix
          path: ".workflows"
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - id: fly_deploy
        run: |
          # Deploy the app to fly.io

          workflow_secrets='${{ toJSON(secrets) }}'
          workflow_inputs='${{ toJSON(inputs) }}'
          workflow_event="$(cat "$GITHUB_EVENT_PATH" | jq -rS '{number, pull_request_head_sha: .pull_request.head.sha}')"

          source .workflows/scripts/fly_deploy.sh
